import { initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

initializeApp();
const db = getFirestore();

const recettes = [
  { nom: "Soupe à l'oignon", univers: "cuisine", sousCategorie: "soupe", ingredients: "4 oignons\n50g de beurre\n1L de bouillon de boeuf\n4 tranches de pain\n100g de gruyère râpé\nSel, poivre", etapes: "Émincer les oignons\nLes faire revenir dans le beurre 20 min\nAjouter le bouillon et mijoter 20 min\nVerser dans des bols, poser le pain et le gruyère\nGratiner au four 10 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Quiche Lorraine", univers: "cuisine", sousCategorie: "plat", ingredients: "1 pâte brisée\n200g de lardons\n3 oeufs\n200ml de crème fraîche\n100g de gruyère\nSel, poivre", etapes: "Préchauffer le four à 180°C\nFoncer un moule avec la pâte\nFaire revenir les lardons\nMélanger oeufs, crème, gruyère\nVerser sur la pâte et cuire 35 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Boeuf Bourguignon", univers: "cuisine", sousCategorie: "plat", ingredients: "1kg de boeuf\n75cl de vin rouge\n200g de lardons\n2 carottes\n1 oignon\n2 gousses d'ail\nBouquet garni", etapes: "Couper le boeuf en cubes\nFaire revenir lardons et légumes\nAjouter le boeuf et le vin\nMijoter 2h30 à feu doux", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Gratin Dauphinois", univers: "cuisine", sousCategorie: "accompagnement", ingredients: "1kg de pommes de terre\n50cl de crème fraîche\n2 gousses d'ail\n50g de beurre\nNoix de muscade\nSel, poivre", etapes: "Préchauffer le four à 160°C\nCouper les pommes de terre en fines tranches\nDisposer en couches dans un plat beurré\nVerser la crème assaisonnée\nCuire 1h30", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Ratatouille", univers: "cuisine", sousCategorie: "accompagnement", ingredients: "2 courgettes\n2 aubergines\n3 tomates\n2 poivrons\n1 oignon\nHuile d'olive\nHerbes de Provence", etapes: "Couper tous les légumes en dés\nFaire revenir l'oignon\nAjouter les légumes un par un\nAssaisonner et mijoter 45 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Poulet rôti", univers: "cuisine", sousCategorie: "plat", ingredients: "1 poulet entier\n50g de beurre\n4 gousses d'ail\n1 citron\nThym, romarin\nSel, poivre", etapes: "Préchauffer le four à 200°C\nFarcir avec ail, citron et herbes\nBeurrer et assaisonner\nCuire 1h15 en arrosant régulièrement", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Blanquette de veau", univers: "cuisine", sousCategorie: "plat", ingredients: "1kg de veau\n2 carottes\n200g de champignons\n30cl de crème fraîche\n2 jaunes d'oeufs\nBouquet garni", etapes: "Faire bouillir le veau avec les légumes\nCuire 1h30\nPréparer une sauce crème avec le bouillon\nAjouter les champignons poêlés", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tartiflette", univers: "cuisine", sousCategorie: "plat", ingredients: "1kg de pommes de terre\n200g de lardons\n1 reblochon\n2 oignons\n10cl de vin blanc", etapes: "Cuire les pommes de terre\nFaire revenir oignons et lardons\nAjouter le vin blanc\nMélanger avec les pommes de terre\nPoser le reblochon et gratiner 25 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Moules marinières", univers: "cuisine", sousCategorie: "plat", ingredients: "2kg de moules\n2 échalotes\n20cl de vin blanc\n30g de beurre\nPersil\nSel, poivre", etapes: "Nettoyer les moules\nFaire revenir les échalotes dans le beurre\nAjouter le vin blanc et les moules\nCouvrir et cuire 5 min\nParsemer de persil", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Soupe de poireaux", univers: "cuisine", sousCategorie: "soupe", ingredients: "4 poireaux\n3 pommes de terre\n1L de bouillon\n20cl de crème fraîche\n30g de beurre", etapes: "Faire revenir les poireaux dans le beurre\nAjouter pommes de terre et bouillon\nCuire 25 min\nMixer et ajouter la crème", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tarte à l'oignon", univers: "cuisine", sousCategorie: "entrée", ingredients: "1 pâte brisée\n6 oignons\n3 oeufs\n20cl de crème fraîche\n50g de beurre\nThym", etapes: "Faire fondre les oignons dans le beurre 30 min\nMélanger oeufs et crème\nAjouter les oignons\nVerser sur la pâte et cuire 30 min à 180°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Salade Niçoise", univers: "cuisine", sousCategorie: "salade", ingredients: "200g de thon\n4 oeufs durs\n200g de haricots verts\n4 tomates\nOlives noires\nAnchois\nHuile d'olive", etapes: "Cuire les haricots verts\nCuire les oeufs durs\nCouper les légumes\nDisposer tous les ingrédients\nAssaisonner", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Gougères", univers: "cuisine", sousCategorie: "apéro", ingredients: "25cl d'eau\n100g de beurre\n150g de farine\n4 oeufs\n100g de gruyère râpé\nSel, poivre", etapes: "Faire bouillir eau et beurre\nAjouter la farine et dessécher\nIncorporer les oeufs un par un\nAjouter le gruyère\nCuire 25 min à 200°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tapenade", univers: "cuisine", sousCategorie: "apéro", ingredients: "200g d'olives noires\n50g de câpres\n4 anchois\n1 gousse d'ail\nHuile d'olive\nJus de citron", etapes: "Mixer olives, câpres, anchois et ail\nAjouter l'huile progressivement\nAssaisonner avec citron\nServir sur des toasts", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Soufflé au fromage", univers: "cuisine", sousCategorie: "entrée", ingredients: "40g de beurre\n40g de farine\n25cl de lait\n4 oeufs\n100g de gruyère râpé\nNoix de muscade", etapes: "Préparer une béchamel\nAjouter les jaunes et le gruyère\nMonter les blancs en neige\nIncorporer délicatement\nCuire 20 min à 190°C sans ouvrir", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Velouté de butternut", univers: "cuisine", sousCategorie: "soupe", ingredients: "1 courge butternut\n1 oignon\n2 carottes\n1L de bouillon\n20cl de crème fraîche\nNoix de muscade", etapes: "Éplucher et couper les légumes\nFaire revenir l'oignon\nAjouter légumes et bouillon\nCuire 25 min et mixer\nAjouter la crème", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Taboulé", univers: "cuisine", sousCategorie: "salade", ingredients: "200g de semoule\n2 tomates\n1 concombre\nMenthe fraîche\nPersil\nJus de 2 citrons\nHuile d'olive", etapes: "Réhydrater la semoule\nCouper les légumes en dés\nCiseler les herbes\nMélanger tout\nAssaisonner et réfrigérer 1h", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Oeufs en meurette", univers: "cuisine", sousCategorie: "entrée", ingredients: "4 oeufs\n50cl de vin rouge\n100g de lardons\n1 oignon\n1 carotte\nBouquet garni\n30g de beurre", etapes: "Réduire le vin avec les légumes\nFiltrer la sauce et la lier au beurre\nPocher les oeufs dans l'eau vinaigrée\nServir nappés de sauce avec lardons", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Brandade de morue", univers: "cuisine", sousCategorie: "plat", ingredients: "500g de morue dessalée\n30cl d'huile d'olive\n20cl de lait\n2 gousses d'ail\nJus de citron", etapes: "Pocher la morue dans le lait\nÉmietter le poisson\nÉcraser avec l'ail\nMonter avec huile et lait chaud alternés\nServir avec des croûtons", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Crêpes sucrées", univers: "pâtisserie", sousCategorie: "viennoiserie", ingredients: "250g de farine\n3 oeufs\n50cl de lait\n50g de beurre fondu\n2 cuillères de sucre\n1 pincée de sel", etapes: "Mélanger farine, sucre et sel\nAjouter les oeufs puis le lait\nIncorporer le beurre fondu\nReposer 30 min\nCuire dans une poêle beurrée", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tarte Tatin", univers: "pâtisserie", sousCategorie: "tarte", ingredients: "1 pâte feuilletée\n6 pommes\n150g de sucre\n80g de beurre\nSucre vanillé", etapes: "Faire un caramel dans un moule\nDisposer les pommes sur le caramel\nRecouvrir de pâte feuilletée\nCuire 30 min à 180°C\nRetourner à la sortie du four", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Mousse au chocolat", univers: "pâtisserie", sousCategorie: "crème/mousse", ingredients: "200g de chocolat noir\n6 oeufs\n30g de sucre\n1 pincée de sel", etapes: "Faire fondre le chocolat\nMélanger avec les jaunes\nMonter les blancs en neige\nIncorporer délicatement\nRéfrigérer 2h", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Crème brûlée", univers: "pâtisserie", sousCategorie: "crème/mousse", ingredients: "50cl de crème liquide\n6 jaunes d'oeufs\n100g de sucre\n1 gousse de vanille\nCassonade", etapes: "Faire chauffer la crème avec la vanille\nMélanger jaunes et sucre\nIncorporer la crème chaude\nCuire au bain-marie 45 min\nCaraméliser au chalumeau", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Madeleine", univers: "pâtisserie", sousCategorie: "biscuit", ingredients: "3 oeufs\n150g de sucre\n150g de farine\n150g de beurre\n1 sachet de levure\n1 citron (zeste)", etapes: "Mélanger oeufs et sucre\nAjouter farine, levure et zeste\nIncorporer le beurre fondu\nRéfrigérer 1h\nCuire 5 min à 220°C puis 8 min à 180°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Quatre-quarts", univers: "pâtisserie", sousCategorie: "gâteau", ingredients: "4 oeufs\n200g de sucre\n200g de beurre\n200g de farine\n1 sachet de levure\n1 citron", etapes: "Mélanger oeufs et sucre\nAjouter farine et levure\nIncorporer le beurre fondu\nVerser dans un moule\nCuire 45 min à 180°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Spaghetti Carbonara", univers: "cuisine", sousCategorie: "plat", ingredients: "400g de spaghetti\n200g de guanciale\n4 jaunes d'oeufs\n100g de pecorino\nPoivre noir", etapes: "Cuire les pâtes al dente\nFaire revenir le guanciale\nMélanger jaunes, pecorino et poivre\nMélanger pâtes et guanciale hors du feu\nAjouter la crème d'oeuf en remuant", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Pizza Margherita", univers: "cuisine", sousCategorie: "plat", ingredients: "500g de farine\n7g de levure\n30cl d'eau\n400g de tomates pelées\n250g de mozzarella\nBasilic\nHuile d'olive", etapes: "Préparer la pâte et laisser lever 2h\nÉtaler et garnir de tomates\nAjouter la mozzarella\nCuire 12 min à 250°C\nAjouter le basilic frais", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Risotto aux champignons", univers: "cuisine", sousCategorie: "plat", ingredients: "300g de riz arborio\n300g de champignons\n1 oignon\n15cl de vin blanc\n1L de bouillon\n50g de parmesan\n30g de beurre", etapes: "Faire revenir oignon et champignons\nAjouter le riz et nacrer\nDéglacer au vin blanc\nAjouter le bouillon louche par louche\nMantecare avec beurre et parmesan", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tiramisu", univers: "pâtisserie", sousCategorie: "crème/mousse", ingredients: "500g de mascarpone\n4 oeufs\n100g de sucre\n20cl de café fort\n200g de boudoirs\nCacao en poudre", etapes: "Battre jaunes et sucre\nIncorporer le mascarpone\nMonter les blancs et incorporer\nTremper les boudoirs dans le café\nAlternance boudoirs et crème\nRéfrigérer 4h et saupoudrer de cacao", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Osso Buco", univers: "cuisine", sousCategorie: "plat", ingredients: "4 tranches de jarret de veau\n2 tomates\n1 oignon\n1 carotte\n15cl de vin blanc\nGremolata: citron, ail, persil", etapes: "Fariner et faire dorer le veau\nFaire revenir les légumes\nAjouter vin blanc et tomates\nMijoter 1h30\nServir avec la gremolata", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Pesto Genovese", univers: "cuisine", sousCategorie: "sauce", ingredients: "50g de basilic frais\n30g de pignons\n50g de parmesan\n1 gousse d'ail\n10cl d'huile d'olive\nSel", etapes: "Mixer basilic, pignons et ail\nAjouter le parmesan\nIncorporer l'huile progressivement\nAssaisonner\nConserver au frais", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Ramen", univers: "cuisine", sousCategorie: "soupe", ingredients: "400g de nouilles ramen\n1L de bouillon de porc\n2 oeufs mollets\n200g de porc chashu\nNori\nBambou mariné\nOignon vert", etapes: "Préparer le bouillon de porc 3h\nCuire la viande roulée en chashu\nCuire les oeufs 7 min\nCuire les nouilles\nAssembler le bol avec tous les éléments", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Sushi Maki", univers: "cuisine", sousCategorie: "entrée", ingredients: "300g de riz à sushi\n6cl de vinaigre de riz\n200g de saumon\n1 concombre\nFeuilles de nori\nWasabi, gingembre", etapes: "Cuire et assaisonner le riz\nPoser le nori sur la natte\nÉtaler le riz et garnir\nRouler fermement\nCouper en tranches de 2cm", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Pad Thaï", univers: "cuisine", sousCategorie: "plat", ingredients: "200g de nouilles de riz\n200g de crevettes\n2 oeufs\n100g de pousses de soja\n3 cuillères de sauce poisson\n2 cuillères de sucre\nCacahuètes, citron vert", etapes: "Tremper les nouilles\nFaire sauter crevettes et oeufs\nAjouter nouilles et sauce\nAjouter pousses de soja\nServir avec cacahuètes et citron", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Curry vert thaï", univers: "cuisine", sousCategorie: "plat", ingredients: "400ml de lait de coco\n2 cuillères de pâte curry vert\n400g de poulet\n1 aubergine thaïe\nFeuilles de kaffir\nSauce poisson\nBasilic thaï", etapes: "Faire revenir la pâte de curry\nAjouter le lait de coco\nAjouter le poulet et l'aubergine\nAssaisonner avec sauce poisson\nAjouter le basilic en fin de cuisson", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Dim Sum vapeur", univers: "cuisine", sousCategorie: "apéro", ingredients: "200g de porc haché\n100g de crevettes\n1 cuillère de sauce soja\n1 cuillère d'huile de sésame\nGingembre frais\nPâte à raviolis", etapes: "Mélanger porc, crevettes et assaisonnements\nFarcir les disques de pâte\nReplier en forme de ravioli\nCuire à la vapeur 12 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Bo Bun", univers: "cuisine", sousCategorie: "salade", ingredients: "200g de boeuf\n150g de vermicelles de riz\nSalade, menthe, coriandre\n100g de pousses de soja\nCarottes râpées\nSauce nuoc mam\nCacahuètes", etapes: "Mariner et griller le boeuf\nCuire les vermicelles\nPréparer la sauce nuoc mam\nAssembler dans un bol\nParsemer de cacahuètes", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Bibimbap", univers: "cuisine", sousCategorie: "plat", ingredients: "300g de riz\n200g de boeuf haché\n2 carottes\n200g d'épinards\n2 oeufs\nSauce gochujang\nHuile de sésame", etapes: "Cuire le riz\nFaire sauter les légumes séparément\nFaire revenir le boeuf avec sauce soja\nDisposer dans un bol sur le riz\nAjouter l'oeuf et la sauce gochujang", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tacos al Pastor", univers: "cuisine", sousCategorie: "plat", ingredients: "500g de porc\n3 piments séchés\n1 ananas\nOignon, coriandre\nTortillas de maïs\nLime\nSel, cumin", etapes: "Mariner le porc dans les piments et épices\nGriller la viande\nChauffer les tortillas\nGarnir avec viande, ananas, oignon et coriandre\nServir avec lime", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Guacamole", univers: "cuisine", sousCategorie: "apéro", ingredients: "3 avocats\n1 tomate\n1 oignon rouge\n1 citron vert\nCoriandre fraîche\nPiment jalapeño\nSel", etapes: "Écraser les avocats\nAjouter tomate et oignon coupés fin\nCiseler la coriandre\nAssaisonner avec citron et sel\nAjouter le piment selon goût", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Enchiladas", univers: "cuisine", sousCategorie: "plat", ingredients: "8 tortillas\n400g de poulet effiloché\n400g de sauce enchilada\n200g de fromage râpé\n1 oignon\nCrema mexicana", etapes: "Mélanger poulet et sauce\nRemplir les tortillas et rouler\nDisposer dans un plat\nNapper de sauce et fromage\nCuire 20 min à 180°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Chili con Carne", univers: "cuisine", sousCategorie: "plat", ingredients: "500g de boeuf haché\n400g de haricots rouges\n400g de tomates\n2 piments\n1 oignon\nCumin, paprika fumé\n1 carré de chocolat noir", etapes: "Faire revenir oignon et viande\nAjouter épices et tomates\nIncorporer les haricots\nAjouter le chocolat\nMijoter 45 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Quesadillas", univers: "cuisine", sousCategorie: "apéro", ingredients: "4 tortillas de blé\n200g de fromage fondu\n200g de poulet grillé\n1 poivron\n1 oignon\nSour cream", etapes: "Garnir une tortilla de fromage, poulet et légumes\nRecouvrir d'une autre tortilla\nCuire à la poêle 3 min de chaque côté\nCouper en quartiers et servir avec sour cream", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Butter Chicken", univers: "cuisine", sousCategorie: "plat", ingredients: "600g de poulet\n400g de tomates\n20cl de crème\n2 oignons\nGingembre, ail\nGaram masala, curcuma, cumin\n50g de beurre", etapes: "Mariner le poulet dans les épices et yaourt\nGriller le poulet\nPréparer la sauce tomate aux épices\nAjouter la crème et le beurre\nIncorporer le poulet et mijoter 15 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Dal de lentilles", univers: "cuisine", sousCategorie: "plat", ingredients: "300g de lentilles corail\n400g de tomates\n1 oignon\n3 gousses d'ail\nGingembre\nCurcuma, cumin, coriandre\n20cl de lait de coco", etapes: "Cuire les lentilles\nFaire revenir oignon, ail et épices\nAjouter tomates et lait de coco\nIncorporer les lentilles\nMijoter 20 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Samosas", univers: "cuisine", sousCategorie: "apéro", ingredients: "200g de pommes de terre\n100g de petits pois\n1 oignon\nCumin, coriandre, gingembre\nPâte filo\nHuile de friture", etapes: "Cuire et écraser les pommes de terre\nMélanger avec petits pois et épices\nFormer des triangles avec la pâte filo\nFarcir et sceller\nFrire jusqu'à dorure", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Naan au beurre", univers: "pâtisserie", sousCategorie: "pain", ingredients: "300g de farine\n150ml de yaourt\n1 sachet de levure\n1 cuillère de sucre\n50g de beurre fondu\nAil et coriandre", etapes: "Mélanger farine, levure, sucre et sel\nAjouter le yaourt et pétrir\nLaisser lever 1h\nFormer des ovales et cuire à la poêle très chaude\nBadigeonner de beurre à l'ail", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tajine de poulet aux olives", univers: "cuisine", sousCategorie: "plat", ingredients: "1 poulet coupé\n200g d'olives vertes\n2 citrons confits\n2 oignons\nCoriandre, gingembre\nCurcuma, safran\nHuile d'olive", etapes: "Mariner le poulet dans les épices\nFaire revenir oignons et poulet\nAjouter olives et citrons confits\nCouvrir et mijoter 45 min\nServir avec de la coriandre", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Couscous royal", univers: "cuisine", sousCategorie: "plat", ingredients: "500g de semoule\n400g d'agneau\n2 merguez\n2 carottes\n2 courgettes\n400g de pois chiches\nRas el hanout\nHarissa", etapes: "Cuire la viande avec les épices et légumes\nPréparer la semoule\nCuire les merguez\nServir avec le bouillon et la harissa", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Pastilla au poulet", univers: "cuisine", sousCategorie: "entrée", ingredients: "1 poulet\n6 feuilles de brick\n3 oeufs\n100g d'amandes\n2 oignons\nCannelle, gingembre, safran\nSucre glace", etapes: "Cuire le poulet avec oignons et épices\nEffilocher la viande\nPréparer une omelette aux oignons\nMonter la pastilla en couches\nCuire au four et saupoudrer de sucre et cannelle", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Houmous", univers: "cuisine", sousCategorie: "apéro", ingredients: "400g de pois chiches\n3 cuillères de tahini\n2 gousses d'ail\nJus de 2 citrons\nHuile d'olive\nCumin\nSel", etapes: "Égoutter et rincer les pois chiches\nMixer avec tahini, ail et citron\nAjuster la texture avec l'eau de cuisson\nAssaisonner\nServir avec huile d'olive et paprika", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Falafel", univers: "cuisine", sousCategorie: "apéro", ingredients: "400g de pois chiches secs\n1 oignon\n4 gousses d'ail\nCoriandre, cumin, persil\nFarine\nHuile de friture", etapes: "Tremper les pois chiches 12h\nMixer avec herbes et épices\nFormer des boulettes\nRéfrigérer 30 min\nFrire jusqu'à dorure", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Moussaka", univers: "cuisine", sousCategorie: "plat", ingredients: "500g d'agneau haché\n3 aubergines\n400g de tomates\n1 oignon\nCannelle, all spice\nBéchamel: beurre, farine, lait, oeuf", etapes: "Faire revenir la viande avec tomates et épices\nGriller les tranches d'aubergines\nPréparer la béchamel\nMonter en couches: aubergines, viande, béchamel\nCuire 45 min à 180°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Spanakopita", univers: "cuisine", sousCategorie: "entrée", ingredients: "500g d'épinards\n200g de feta\n3 oeufs\n1 oignon\nAneth frais\n8 feuilles de pâte filo\nHuile d'olive", etapes: "Faire revenir épinards et oignon\nMélanger avec feta, oeufs et aneth\nBeurrer les feuilles de filo\nGarnir et plier en triangles\nCuire 25 min à 180°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Paella Valenciana", univers: "cuisine", sousCategorie: "plat", ingredients: "400g de riz rond\n300g de poulet\n200g de lapin\n200g de haricots verts\n400g de tomates\nSafran, paprika fumé\nHuile d'olive", etapes: "Faire revenir viande dans la paellera\nAjouter légumes et tomates\nAjouter le riz et nacrer\nAjouter bouillon chaud et safran\nCuire 18 min sans remuer", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Gazpacho", univers: "cuisine", sousCategorie: "soupe", ingredients: "1kg de tomates\n1 concombre\n1 poivron rouge\n1 gousse d'ail\n5cl de vinaigre de Xérès\n10cl d'huile d'olive\nSel", etapes: "Couper tous les légumes\nMixer finement\nAjouter vinaigre et huile\nAssaisonner\nRéfrigérer 2h et servir bien frais", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Patatas Bravas", univers: "cuisine", sousCategorie: "apéro", ingredients: "1kg de pommes de terre\nSauce brava: tomates, paprika fort, ail\nAioli: mayonnaise, ail\nHuile de friture\nSel", etapes: "Couper les pommes de terre en cubes\nFrire jusqu'à dorure\nPréparer la sauce brava\nPréparer l'aioli\nServir arrosé des deux sauces", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Hamburger maison", univers: "cuisine", sousCategorie: "plat", ingredients: "500g de boeuf haché\n4 buns briochés\n4 tranches de cheddar\nSalade, tomate, oignon\nKetchup, moutarde, mayo\nCornichons", etapes: "Former des steaks de 125g\nCuire à la poêle très chaude 3 min par face\nFaire fondre le cheddar\nToaster les buns\nAssembler avec toutes les garnitures", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Cheesecake New-Yorkais", univers: "pâtisserie", sousCategorie: "gâteau", ingredients: "200g de spéculoos\n80g de beurre\n600g de cream cheese\n150g de sucre\n3 oeufs\n20cl de crème fraîche\n1 citron", etapes: "Écraser les spéculoos et mélanger au beurre\nTasser dans un moule\nBattre cream cheese et sucre\nAjouter oeufs et crème\nCuire 1h à 160°C au bain-marie\nRéfrigérer une nuit", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Brownies", univers: "pâtisserie", sousCategorie: "gâteau", ingredients: "200g de chocolat noir\n150g de beurre\n200g de sucre\n3 oeufs\n80g de farine\n100g de noix", etapes: "Faire fondre chocolat et beurre\nAjouter sucre et oeufs\nIncorporer la farine\nAjouter les noix\nCuire 20 min à 180°C - le centre doit rester fondant", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Gyoza", univers: "cuisine", sousCategorie: "apéro", ingredients: "200g de porc haché\n200g de chou chinois\n2 gousses d'ail\nGingembre frais\nSauce soja, huile de sésame\nPâte à gyoza", etapes: "Mélanger porc, chou et assaisonnements\nFarcir les disques de pâte\nPlier et sceller en plissant\nPoêler 2 min puis ajouter eau\nCouvrir et cuire vapeur 5 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Soupe miso", univers: "cuisine", sousCategorie: "soupe", ingredients: "1L de dashi\n3 cuillères de miso blanc\n150g de tofu soyeux\nAlgues wakamé\nOignon vert", etapes: "Préparer le dashi\nDissoudre le miso dans un peu de dashi\nAjouter au bouillon chaud\nAjouter tofu et algues\nServir avec oignon vert", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Ceviche", univers: "cuisine", sousCategorie: "entrée", ingredients: "500g de cabillaud frais\n10 citrons verts\n1 oignon rouge\n2 piments\nCoriandre fraîche\nSel, poivre", etapes: "Couper le poisson en dés\nMariner dans le jus de citron 15 min\nAjouter oignon rouge en lamelles\nAjouter piment et coriandre\nServir immédiatement bien frais", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tarte au citron", univers: "pâtisserie", sousCategorie: "tarte", ingredients: "1 pâte sablée\n4 citrons\n4 oeufs\n150g de sucre\n80g de beurre", etapes: "Cuire la pâte à blanc 15 min\nPréparer la crème citron avec jus, zestes, oeufs, sucre et beurre\nVerser sur la pâte\nCuire 15 min à 170°C\nLaisser refroidir", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Clafoutis aux cerises", univers: "pâtisserie", sousCategorie: "gâteau", ingredients: "500g de cerises\n3 oeufs\n100g de sucre\n60g de farine\n30cl de lait\n20g de beurre", etapes: "Préchauffer le four à 180°C\nBeurrer un moule et disposer les cerises\nMélanger oeufs, sucre, farine et lait\nVerser sur les cerises\nCuire 35 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Financiers", univers: "pâtisserie", sousCategorie: "biscuit", ingredients: "150g de beurre\n200g de sucre glace\n80g de farine\n80g de poudre d'amande\n5 blancs d'oeufs", etapes: "Faire un beurre noisette\nMélanger sucre glace, farine et amande\nAjouter les blancs non montés\nIncorporer le beurre noisette\nCuire 12 min à 200°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Confiture de fraises", univers: "pâtisserie", sousCategorie: "confiture", ingredients: "1kg de fraises\n800g de sucre\nJus d'un citron", etapes: "Laver et équeuter les fraises\nMélanger avec sucre et citron\nMacérer une nuit\nPorter à ébullition\nCuire 25 min et mettre en pots", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Pain maison", univers: "pâtisserie", sousCategorie: "pain", ingredients: "500g de farine\n7g de levure\n10g de sel\n30cl d'eau tiède", etapes: "Diluer la levure dans l'eau\nMélanger farine et sel\nPétrir 10 min\nLaisser lever 1h\nFormer et laisser lever 30 min\nCuire 30 min à 230°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Galette bretonne", univers: "pâtisserie", sousCategorie: "biscuit", ingredients: "250g de farine\n200g de beurre demi-sel\n150g de sucre\n3 jaunes d'oeufs\nSucre vanillé", etapes: "Mélanger beurre pommade et sucre\nAjouter les jaunes\nIncorporer la farine\nÉtaler dans un moule\nDorer et strier\nCuire 30 min à 170°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Profiteroles", univers: "pâtisserie", sousCategorie: "viennoiserie", ingredients: "Pâte à choux: eau, beurre, farine, oeufs\nGlace vanille\n200g de chocolat noir\n10cl de crème liquide", etapes: "Préparer et cuire la pâte à choux\nLaisser refroidir\nGarnir de glace vanille\nFaire fondre chocolat et crème\nNapper les choux de sauce chaude", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tom Yum Goong", univers: "cuisine", sousCategorie: "soupe", ingredients: "300g de crevettes\n1L de bouillon\n3 feuilles de kaffir\n2 tiges de citronnelle\nGalanga\n200g de champignons\nSauce poisson, piment, citron vert", etapes: "Porter le bouillon à ébullition\nAjouter citronnelle, kaffir et galanga\nAjouter les champignons\nAjouter les crevettes\nAssaisonner avec sauce poisson et citron", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Nasi Goreng", univers: "cuisine", sousCategorie: "plat", ingredients: "300g de riz cuit froid\n200g de crevettes\n2 oeufs\n2 gousses d'ail\nKecap manis\nSauce soja\nOignon vert, piment", etapes: "Faire revenir ail et piment\nAjouter les crevettes\nPousser et faire des oeufs brouillés\nAjouter le riz froid et mélanger\nAssaisonner avec kecap manis", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Pho Bo", univers: "cuisine", sousCategorie: "soupe", ingredients: "1L de bouillon de boeuf\n200g de boeuf tranché fin\n200g de nouilles de riz\nAnis étoilé, cannelle\nGingembre, oignon brûlé\nBasilic thaï, pousses de soja, citron", etapes: "Préparer le bouillon avec épices 3h\nCuire les nouilles\nDisposer dans un bol\nVerser le bouillon bouillant sur le boeuf\nServir avec herbes et condiments", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Churros", univers: "pâtisserie", sousCategorie: "viennoiserie", ingredients: "250g de farine\n25cl d'eau bouillante\n1 pincée de sel\nHuile de friture\nSucre et cannelle\nChocolat chaud pour tremper", etapes: "Mélanger farine, eau bouillante et sel\nFormer une pâte homogène\nMettre dans une poche avec douille étoile\nFrire dans l'huile chaude\nRouler dans le sucre cannelle", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Baklava", univers: "pâtisserie", sousCategorie: "biscuit", ingredients: "400g de pâte filo\n300g de noix mélangées\n200g de beurre fondu\nSirop: eau, sucre, miel, eau de rose", etapes: "Beurrer les feuilles de filo en alternant avec les noix\nCouper en losanges\nCuire 30 min à 180°C\nVerser le sirop chaud sur le baklava froid", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Shakshuka", univers: "cuisine", sousCategorie: "plat", ingredients: "6 oeufs\n400g de tomates\n2 poivrons\n1 oignon\n3 gousses d'ail\nCumin, paprika, piment\nFeta, persil", etapes: "Faire revenir oignon, poivrons et ail\nAjouter tomates et épices\nMijoter 15 min\nCasser les oeufs dans la sauce\nCouvrir et cuire 8 min\nParsemer de feta et persil", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tarte aux pommes", univers: "pâtisserie", sousCategorie: "tarte", ingredients: "1 pâte brisée\n6 pommes\n50g de sucre\n30g de beurre\n1 sachet de sucre vanillé\nCannelle", etapes: "Préchauffer le four à 180°C\nÉplucher et couper les pommes\nFoncer le moule avec la pâte\nDisposer les pommes en rosace\nSaupoudrer de sucre et beurre\nCuire 35 min", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Soupe à la tomate", univers: "cuisine", sousCategorie: "soupe", ingredients: "1kg de tomates\n1 oignon\n2 gousses d'ail\n50cl de bouillon\n10cl de crème\nBasilic frais\nHuile d'olive", etapes: "Faire revenir oignon et ail\nAjouter les tomates coupées\nAjouter le bouillon et cuire 20 min\nMixer finement\nAjouter la crème et le basilic", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Sauce hollandaise", univers: "cuisine", sousCategorie: "sauce", ingredients: "3 jaunes d'oeufs\n200g de beurre clarifié\nJus de citron\n2 cuillères d'eau\nSel, poivre blanc", etapes: "Battre les jaunes avec l'eau au bain-marie\nAjouter le beurre clarifié en filet\nAssaisonner avec citron et sel\nServir immédiatement", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Poulet tikka masala", univers: "cuisine", sousCategorie: "plat", ingredients: "600g de poulet\n400g de tomates\n20cl de crème\n1 oignon\nAil, gingembre\nTikka masala, curcuma, cumin\nYaourt pour marinade", etapes: "Mariner le poulet dans yaourt et épices\nGriller le poulet au four\nPréparer la sauce masala aux tomates\nAjouter la crème\nIncorporer le poulet et mijoter", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Dumplings chinois", univers: "cuisine", sousCategorie: "apéro", ingredients: "200g de porc haché\n200g de chou\n2 oignons verts\nGingembre, sauce soja\nHuile de sésame\nPâte à dumplings", etapes: "Mélanger porc, chou et assaisonnements\nFarcir les disques de pâte\nPlier en demi-lune\nCuire à la vapeur ou poêler\nServir avec sauce soja et vinaigre", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Mole Poblano", univers: "cuisine", sousCategorie: "sauce", ingredients: "5 piments séchés\n50g de chocolat noir\n2 tomates\n1 oignon\n2 gousses d'ail\nCumin, cannelle\nSésame, amandes", etapes: "Griller et réhydrater les piments\nFaire revenir tomates, oignon et ail\nMixer avec épices et fruits secs\nAjouter le chocolat\nMijoter 30 min en remuant", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Pulled Pork", univers: "cuisine", sousCategorie: "plat", ingredients: "1.5kg d'épaule de porc\n2 cuillères de paprika fumé\n1 cuillère de cumin\nCassonade, sel, poivre\n20cl de bouillon\nSauce BBQ", etapes: "Frotter la viande avec les épices\nLaisser mariner une nuit\nCuire au four 6h à 150°C\nEffilocher la viande\nMélanger avec la sauce BBQ\nServir en sandwich", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Salade grecque", univers: "cuisine", sousCategorie: "salade", ingredients: "3 tomates\n1 concombre\n1 oignon rouge\n200g de feta\nOlives kalamata\nOrigan\nHuile d'olive, vinaigre de vin", etapes: "Couper les légumes en gros morceaux\nDisposer dans un plat\nAjouter les olives et la feta en bloc\nArroser d'huile d'olive\nSaupoudrer d'origan", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Curry japonais", univers: "cuisine", sousCategorie: "plat", ingredients: "400g de poulet\n2 pommes de terre\n2 carottes\n1 oignon\n100g de roux à curry japonais\n80cl d'eau\nRiz japonais", etapes: "Faire revenir oignon, poulet et légumes\nAjouter l'eau et cuire 20 min\nAjouter le roux à curry et mélanger\nMijoter 10 min jusqu'à épaississement\nServir sur le riz", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Empanadas", univers: "cuisine", sousCategorie: "apéro", ingredients: "300g de farine\n100g de beurre\n1 oeuf\n300g de boeuf haché\n1 oignon\n1 oeuf dur\nOlives, cumin, paprika", etapes: "Préparer la pâte brisée\nFaire revenir boeuf et oignon avec épices\nAjouter oeuf dur et olives\nFormer des disques et farcir\nSceller et dorer\nCuire 20 min à 200°C", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tarte aux fraises", univers: "pâtisserie", sousCategorie: "tarte", ingredients: "1 pâte sablée\n500g de fraises\n30cl de lait\n3 jaunes d'oeufs\n80g de sucre\n30g de farine\n1 gousse de vanille", etapes: "Cuire la pâte à blanc\nPréparer la crème pâtissière\nLaisser refroidir\nÉtaler la crème sur la pâte\nDisposer les fraises coupées\nNapper de gelée de groseilles", estPublic: true, auteurId: "admin", image: "" },
  { nom: "Tajine d'agneau aux pruneaux", univers: "cuisine", sousCategorie: "plat", ingredients: "800g d'agneau\n200g de pruneaux\n2 oignons\n50g d'amandes\nCannelle, gingembre, safran\nMiel\nHuile d'olive", etapes: "Faire revenir l'agneau avec oignons et épices\nAjouter les pruneaux et le miel\nCouvrir et mijoter 1h30\nFaire dorer les amandes\nServir parsemé d'amandes grillées", estPublic: true, auteurId: "admin", image: "" }
];

async function main() {
  console.log("Injection de " + recettes.length + " recettes...");
  for (const recette of recettes) {
    await db.collection("recettes").add(recette);
    console.log("OK: " + recette.nom);
  }
  console.log("Termine !");
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
